clear all; % Clears old variables.
clc; % Clears command window.
clf; % Clears figures.
%close all; % Closes any open windows.

%% LaTeX stuff.
set(groot, 'defaultAxesTickLabelInterpreter','latex');
set(groot, 'defaultTextInterpreter','latex');
set(groot, 'defaultLegendInterpreter','latex');

% Specify the 'prefix' folder, i.e. not the name generated by the Fortran program.
%prefix = '';
%prefix = 'automatedRun/512/';
%prefix = 'debug/';
prefix = 'recreation/';
%prefix = 'J_str/';
%prefix = 'PBCvsFBC/';
%prefix = 'solventDistribution/';
%prefix = 'topView/';

% Declare global variables
global lambda L

% Get the subfolders in the prefix directory as an array.
subFolders = listDirsLocal(prefix);

% Loop over the size of the subFolders array.
for k = 1:size(subFolders)
    % Update folder & directory and extract the parameters from the directory name.
    folder = subFolders(k).name;
    directory = [prefix folder];
    [lambda, L, numIters] = findParamaters(directory,0);
    
    % Query the folder to determine the number of .dat files.
    a = dir([directory '/*.dat']); b = numel(a);
    
    % Loop over the number of .dat files.
    for n = 1:b
        % Import the frame.
        frame = importdata([directory '/frame-' num2str(n) '.dat']);
        
        % Calculate the concentration of zeros (for the whole lattice) and the number of MCS.
        c0 = 1 - nnz(frame)/numel(frame); MCS = numIters*(n-1)/(size(frame,1)*size(frame,2));
        
        % Save c0 as c0_in on the first run.
        if n == 1
            c0_in = c0;
        end
        
        % Break & save if c0 = 0.5*c0_in.
        if(c0 == 0.5*c0_in)
            break;
        end
    end
end

function subFolders = listDirsLocal(temp)
    % Get a list of all files and folders in this folder.
    files = dir(temp);
    % Get a logical vector that tells which is a directory.
    dirFlags = [files.isdir];
    % Extract only those that are directories and remove '.' and '..'.
    subFolders = files(dirFlags);
    for k = 1 : length(subFolders)
        x(k) = sum(subFolders(k).name ~= '.') ~= 0;
    end
    subFolders = subFolders(x~=0);
end